data:
  hr_images_path = ""
  val_split: 0.2
  test_split: 0.1
  batch_size: 4
  hr_size: 256
  lr_size: 64


training:
  batch_size: 4
  num_epochs: 50
  learning_rate: 1e-4
  reduce_lr_wait: 5
  early_stop_patience: 10
  early_stopping: true
  improvement_epsilon: 1e-4
  checkpoints_dir = "checkpoints"


model:
  num_channels: 64
  scale_factor: 4
  num_blocks: 16
