data:
  hr_images_path: C:/Users/Hammad/Desktop/image-sr/data/DIV2K_train
  batch_size: 4
  hr_size: 256
  lr_size: 64


training:
  batch_size: 4
  num_epochs: 50
  learning_rate: 0.0001
  reduce_lr_wait: 5
  early_stop_patience: 10
  improvement_epsilon: 1e-4
  checkpoints_dir: "checkpoints"


model:
  num_channels: 64
  scale_factor: 4
  num_blocks: 16
